name: AQI on Github Actions
on:
  push:
  schedule:
    - cron: '0 18 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - run: |
          # install dependencies
          pip install requests pandas sqlalchemy

          # set environment variables
          export DATABASE_URL=${secrets.DATABASE_URL}
          export WAQI_API_KEY=${secrets.WAQI_API_KEY}
      
      - uses: actions/python@v2
        with:
          entrypoint: aqioperator.py
          arguments: save_aqi_data
